//Orders Types
export const FORM_ORDER = 'FORM_ORDER'
export const GET_ORDERS = 'GET_ORDERS'
export const ADD_ORDER = 'ADD_ORDER'
export const VALIDATE_FORM = 'VALIDATE_FORM'
export const ACTUAL_ORDER = 'ACTUAL_ORDER'
export const DELETE_ORDER = 'DELETE_ORDER'
export const GET_ARTICLES = 'GET_ARTICLES'
export const SELECT_ARTICLE = 'SELECT_ARTICLE'
export const DELETE_SELECTED_ARTICLE = 'DELETE_SELECTED_ARTICLE'
export const GET_PROVIDERS = 'GET_PROVIDERS'
export const SELECT_PROVIDER = 'SELECT_PROVIDER'


//Requisition Types
export const REQUISITION_ARTICLES = 'REQUISITION_ARTICLES'
export const UPDATE_REQUISITION_ARTICLE = 'UPDATE_REQUISITION_ARTICLE'
export const CREATE_REQUISITION = 'CREATE_REQUISITION'
export const CREATE_ERROR = 'CREATE_ERROR'

//Alert Types
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

//Auth types
export const SUCCESSFUL_REGISTER = 'SUCCESSFUL_REGISTER'
export const FAILURE_REGISTER = 'FAILURE_REGISTER'
export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN'
export const FAILURE_LOGIN = 'FAILURE_LOGIN'
export const GET_USER = 'GET_USER'
export const LOGOUT = 'LOGOUT'